version: 1
builder:
  configs:
    - documentation_targets: [SwiftFTR]
      scheme: SwiftFTR
      platform: macos
      swift_version: "6.1"
    - documentation_targets: [SwiftFTR]
      scheme: SwiftFTR
      platform: macos
      swift_version: "6.0"