name: Generate DocC (Reusable)

on:
  workflow_call:
    inputs:
      docs-domain:
        description: 'Domain for documentation site'
        required: false
        type: string
        default: 'swiftftr.networkweather.com'

jobs:
  generate-docc:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate DocC
        env:
          DOCS_DOMAIN: ${{ inputs.docs-domain }}
        run: |
          swift --version
          rm -rf docc
          swift package --allow-writing-to-directory docc \
            generate-documentation --target SwiftFTR \
            --output-path docc \
            --transform-for-static-hosting
          # Add Pages config files
          touch docc/.nojekyll
          echo "$DOCS_DOMAIN" > docc/CNAME
          # Force root redirect to module landing
          cat > docc/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>SwiftFTR Docs</title>
          <meta http-equiv="refresh" content="0; url=/documentation/swiftftr/">
          <link rel="canonical" href="/documentation/swiftftr/">
          <script>location.replace('/documentation/swiftftr/');</script>
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docc