name: Docs (GitHub Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.4 (Swift 5.10)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Generate DocC
        run: |
          swift --version
          rm -rf docs-out
          swift package --allow-writing-to-directory docs-out \
            generate-documentation --target SwiftFTR \
            --output-path docs-out \
            --transform-for-static-hosting \
            --hosting-base-path SwiftFTR
          touch docs-out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

