name: Release (manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag or ref to release (e.g., v0.1.0)'
        required: true

permissions:
  contents: write
  attestations: write
  id-token: write
  actions: read

jobs:
  macos-release:
    name: macOS Release Manual
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Select Xcode 26 (Swift 6.2)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0'

      - name: Swift version
        run: swift --version

      - name: Build (release)
        run: |
          swift build -c release
          cp .build/release/swift-ftr swift-ftr-macos-arm64
          shasum -a 256 swift-ftr-macos-arm64 > swift-ftr-macos-arm64.sha256

      - name: Generate SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.cdx.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swift-ftr-${{ inputs.ref }}-macos-arm64
          path: |
            swift-ftr-macos-arm64
            swift-ftr-macos-arm64.sha256
            sbom.cdx.json

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            swift-ftr-macos-arm64
            swift-ftr-macos-arm64.sha256
            sbom.cdx.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.ref }}
          files: |
            swift-ftr-macos-arm64
            swift-ftr-macos-arm64.sha256
            sbom.cdx.json
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
