name: Release (attested + SBOM)

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write       # create GitHub Releases
  attestations: write   # publish build attestations
  id-token: write       # OIDC for provenance
  actions: read
  pages: write         # deploy docs to GitHub Pages

jobs:
  macos-release:
    name: macOS Release (SwiftPM)
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Build (release)
        run: |
          swift build -c release
          cp .build/release/swift-ftr swift-ftr-macos-arm64
          shasum -a 256 swift-ftr-macos-arm64 > swift-ftr-macos-arm64.sha256

      - name: Generate SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom.cdx.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swift-ftr-${{ github.ref_name }}-macos-arm64
          path: |
            swift-ftr-macos-arm64
            swift-ftr-macos-arm64.sha256
            sbom.cdx.json

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            swift-ftr-macos-arm64
            swift-ftr-macos-arm64.sha256
            sbom.cdx.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            swift-ftr-macos-arm64
            swift-ftr-macos-arm64.sha256
            sbom.cdx.json
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Automatically update DocC documentation when a release is created
  docs-update:
    name: Update DocC Documentation
    needs: macos-release
    runs-on: macos-15
    env:
      DOCS_DOMAIN: swiftftr.networkweather.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate DocC
        run: |
          swift --version
          rm -rf docc
          swift package --allow-writing-to-directory docc \
            generate-documentation --target SwiftFTR \
            --output-path docc \
            --transform-for-static-hosting
          # Add Pages config files
          touch docc/.nojekyll
          echo "$DOCS_DOMAIN" > docc/CNAME
          # Force root redirect to module landing
          cat > docc/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>SwiftFTR Docs</title>
          <meta http-equiv="refresh" content="0; url=/documentation/swiftftr/">
          <link rel="canonical" href="/documentation/swiftftr/">
          <script>location.replace('/documentation/swiftftr/');</script>
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docc

  deploy-docs:
    needs: docs-update
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
